"use client";
import { useCallback,useEffect,useRef,useState } from "react";
type RoomState={videoId:string;playing:boolean;position:number;updatedAt:number;title:string;hostId?:string};
type YTPlayer={cueVideoById:(id:string,startSeconds?:number)=>void;loadVideoById:(id:string,startSeconds?:number)=>void;playVideo:()=>void;pauseVideo:()=>void;seekTo:(seconds:number,allow:boolean)=>void;getCurrentTime:()=>number;getVideoUrl:()=>string};
type YTApi={Player:new(element:HTMLElement,options:Record<string,unknown>)=>YTPlayer;PlayerState:{PLAYING:number;PAUSED:number;BUFFERING:number;ENDED:number}};
declare global{interface Window{YT?:YTApi;onYouTubeIframeAPIReady?:()=>void}}
const EMPTY:RoomState={videoId:"",playing:false,position:0,updatedAt:0,title:"Пока ничего не включено"};
function parseUrl(raw:string){try{const u=new URL(raw.trim()),host=u.hostname.toLowerCase().replace(/^(www|m)\./,"");let id="";if(host==="youtu.be")id=u.pathname.split("/").filter(Boolean)[0]||"";else if(host==="youtube.com"||host.endsWith(".youtube.com")){if(u.pathname==="/watch")id=u.searchParams.get("v")||"";else if(/^\/(shorts|embed|live)\//.test(u.pathname))id=u.pathname.split("/")[2]||"";}return /^[a-zA-Z0-9_-]{11}$/.test(id)?id:null}catch{return null}}
function getRoom(){return location.hash.slice(1).replace(/[^a-zA-Z0-9_-]/g,"").slice(0,80)||"main"}
function getParticipant(){let id=localStorage.getItem("togethertv-participant");if(!id){id=crypto.randomUUID();localStorage.setItem("togethertv-participant",id)}return id}
export default function Home(){
 const[room,setRoom]=useState("main"),[state,setState]=useState<RoomState>(EMPTY),[url,setUrl]=useState(""),[title,setTitle]=useState(""),[suggestion,setSuggestion]=useState(""),[queue,setQueue]=useState<{id:string;videoId:string;title:string;createdAt:number}[]>([]),[participantId,setParticipantId]=useState(""),[hostId,setHostId]=useState(""),[error,setError]=useState(""),[notice,setNotice]=useState(""),[connected,setConnected]=useState(false),[ready,setReady]=useState(false);
 const host=useRef<HTMLDivElement>(null),player=useRef<YTPlayer|null>(null),stateRef=useRef<RoomState>(EMPTY),suppress=useRef(0),isHostRef=useRef(false);
 const isHost=!!participantId&&participantId===hostId;isHostRef.current=isHost;
 useEffect(()=>{setParticipantId(getParticipant());const change=()=>setRoom(getRoom());change();addEventListener("hashchange",change);return()=>removeEventListener("hashchange",change)},[]);
 const loadRoom=useCallback(async()=>{try{const r=await fetch("/api/state?room="+encodeURIComponent(room),{cache:"no-store"});if(!r.ok)throw Error();const x=await r.json();setConnected(true);setHostId(x.hostId||"");if(x.state&&x.state.updatedAt>=stateRef.current.updatedAt){stateRef.current=x.state;setState(x.state)}}catch{setConnected(false);setError("Соединение с комнатой потеряно. Повторяем подключение…")}},[room]);
 useEffect(()=>{stateRef.current=EMPTY;setState(EMPTY);void loadRoom();const t=setInterval(loadRoom,1000);return()=>clearInterval(t)},[loadRoom]);
 const claimHost=async()=>{try{const r=await fetch("/api/state?room="+encodeURIComponent(room),{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"claim",participantId})});const x=await r.json();if(!r.ok)throw Error(x.error||"Не удалось стать ведущим");setHostId(x.hostId);setNotice(x.hostId===participantId?"Вы ведущий этой комнаты. Управление плеером доступно вам.":"У комнаты уже есть ведущий; вы можете предложить следующее видео.");await loadRoom()}catch(e){setError(e instanceof Error?e.message:"Ошибка комнаты")}};
 const publish=useCallback(async(patch:Partial<RoomState>)=>{if(!isHost){setError("Управлять воспроизведением может только ведущий комнаты.");return}const next={...stateRef.current,...patch,updatedAt:Date.now(),hostId};try{const r=await fetch("/api/state?room="+encodeURIComponent(room),{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"update",participantId,...next}),cache:"no-store"});const x=await r.json();if(!r.ok)throw Error(x.error||"Команда отклонена");stateRef.current=x.state||next;setState(stateRef.current);setError("");setConnected(true)}catch(e){setConnected(false);setError(e instanceof Error?e.message:"Не удалось обновить комнату")}},[room,isHost,participantId,hostId]);
 useEffect(()=>{let cancelled=false;const init=()=>{if(cancelled||!host.current||!window.YT?.Player||player.current)return;player.current=new window.YT.Player(host.current,{width:"100%",height:"100%",videoId:"",playerVars:{playsinline:1,controls:1,rel:0,enablejsapi:1,origin:location.origin},events:{onReady:()=>{if(!cancelled)setReady(true)},onError:(e:{data:number})=>{const m:Record<number,string>={2:"Некорректная ссылка на видео.",5:"YouTube не смог воспроизвести это видео.",100:"Видео удалено, скрыто или недоступно.",101:"Владелец запретил встраивание этого видео.",150:"Владелец запретил встраивание этого видео.",153:"YouTube не получил данные о клиенте. Обновите страницу."};setError(m[e.data]||"Видео недоступно для встраивания или ограничено YouTube.")},onStateChange:(e:{data:number})=>{if(!isHostRef.current||Date.now()<suppress.current||!window.YT||!player.current)return;const s=window.YT.PlayerState;if(e.data===s.PLAYING)void publish({playing:true,position:player.current.getCurrentTime()||0});if(e.data===s.PAUSED)void publish({playing:false,position:player.current.getCurrentTime()||0});if(e.data===s.ENDED)void publish({playing:false,position:player.current.getCurrentTime()||0})}}}) as YTPlayer};if(window.YT?.Player)init();else{let script=document.querySelector<HTMLScriptElement>('script[src="https://www.youtube.com/iframe_api"]');if(!script){script=document.createElement("script");script.src="https://www.youtube.com/iframe_api";script.async=true;document.head.appendChild(script)}const old=window.onYouTubeIframeAPIReady;window.onYouTubeIframeAPIReady=()=>{old?.();init()};const t=setInterval(()=>{if(window.YT?.Player){clearInterval(t);init()}},200);const timeout=setTimeout(()=>{clearInterval(t);if(!cancelled&&!window.YT?.Player)setError("Не удалось загрузить YouTube-плеер. Проверьте соединение или блокировщик.")},15000);return()=>{cancelled=true;clearInterval(t);clearTimeout(timeout)}}return()=>{cancelled=true}},[isHost,publish]);
 useEffect(()=>{const p=player.current;if(!p||!ready||!state.videoId)return;suppress.current=Date.now()+1200;const target=state.playing?state.position+Math.max(0,(Date.now()-state.updatedAt)/1000):state.position;try{if(!p.getVideoUrl().includes(state.videoId))p.cueVideoById(state.videoId,target);else{if(Math.abs((p.getCurrentTime()||0)-target)>2)p.seekTo(target,true);if(state.playing)p.playVideo();else p.pauseVideo()}}catch{}},[state.videoId,state.updatedAt,ready]);
 useEffect(()=>{if(!isHost||!ready)return;const t=setInterval(()=>{const p=player.current,s=stateRef.current;if(!p||!s.videoId||!s.playing||Date.now()<suppress.current)return;const actual=p.getCurrentTime()||0,expected=s.position+Math.max(0,(Date.now()-s.updatedAt)/1000);if(Math.abs(actual-expected)>3){suppress.current=Date.now()+500;void publish({position:actual,playing:true})}},2000);return()=>clearInterval(t)},[isHost,ready,publish]);
 const startVideo=async(e:React.FormEvent)=>{e.preventDefault();const videoId=parseUrl(url);if(!videoId){setError("Введите корректную ссылку YouTube: youtube.com/watch?v=…, youtu.be/… или youtube.com/shorts/…");return}setError("");await publish({videoId,title:title.trim()||"YouTube · "+videoId,playing:false,position:0})};
 const suggest=async(e:React.FormEvent)=>{e.preventDefault();const videoId=parseUrl(suggestion);if(!videoId){setError("Вставьте корректную ссылку на YouTube-видео.");return}try{const r=await fetch("/api/queue?room="+encodeURIComponent(room),{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({videoId,title:"YouTube · "+videoId,participantId})});const x=await r.json();if(!r.ok)throw Error(x.error||"Не удалось добавить предложение");setQueue(x.queue||[]);setSuggestion("");setNotice("Предложение добавлено в очередь. Ведущий решит, когда его включить.");setError("")}catch(e){setError(e instanceof Error?e.message:"Не удалось добавить предложение")}};
 const loadQueue=useCallback(async()=>{try{const r=await fetch("/api/queue?room="+encodeURIComponent(room),{cache:"no-store"});if(r.ok){const x=await r.json();setQueue(x.queue||[])}}catch{}},[room]);
 useEffect(()=>{void loadQueue();const t=setInterval(loadQueue,3000);return()=>clearInterval(t)},[loadQueue]);
 const playAll=async()=>{const p=player.current;const position=p?.getCurrentTime()||stateRef.current.position;suppress.current=Date.now()+1000;await publish({playing:true,position});try{p?.playVideo();setNotice("Команда отправлена. Мобильный браузер может потребовать нажатия ▶ на плеере.")}catch{setNotice("Нажмите ▶ на плеере YouTube.")}};
 const pauseAll=async()=>{const position=player.current?.getCurrentTime()||stateRef.current.position;suppress.current=Date.now()+1000;await publish({playing:false,position});player.current?.pauseVideo()};
 const seek=async()=>{suppress.current=Date.now()+1000;await publish({playing:false,position:0});player.current?.seekTo(0,true)};
 return <main><header><div><b className="logo">TogetherTV</b><span className="muted"> watch party</span></div><span className={"connection "+(connected?"online":"offline")}>{connected?"● Комната подключена":"○ Подключение…"}</span></header><div className="room">Комната: <b>{room}</b> <span className="muted">· поделитесь ссылкой с #комната</span></div>
 <section className="hero"><div className="player"><div className="youtubeHost" ref={host}/>{!isHost&&state.videoId&&<div className="guestOverlay" aria-label="Управление плеером доступно только ведущему"/>}{!state.videoId&&<div className="empty"><div className="play">▶</div><h1>Смотрите вместе</h1><p>Ведущий выбирает видео, остальные предлагают следующий ролик.</p></div>}</div><div className="playerStatus"><b>{ready?"YouTube-плеер готов":"Загрузка YouTube-плеера…"}</b><span className="muted">{state.playing?"▶ Воспроизводится":"Ⅱ Пауза"}</span></div><div className="now"><span>Сейчас смотрим</span><strong>{state.title}</strong></div></section>
 <section className="admin"><h2>Комната просмотра</h2><p className="hint">Только ведущий управляет текущим плеером. Остальные участники могут добавлять предложения в очередь.</p>{!hostId?<div className="hostClaim"><p>У этой комнаты пока нет ведущего.</p><button onClick={()=>void claimHost()}>Стать ведущим</button></div>:<p className="hint">{isHost?"Вы ведущий — вам доступно управление воспроизведением.":"Ведущий уже назначен. Вы можете предложить следующее видео."}</p>}
 {isHost&&<><form className="youtubeForm" onSubmit={startVideo}><label htmlFor="youtube-url">Выбрать видео для просмотра (только ведущий)</label><input id="youtube-url" type="url" value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://www.youtube.com/watch?v=…" required/><input aria-label="Название видео" value={title} onChange={e=>setTitle(e.target.value)} placeholder="Название (необязательно)"/><button className="primaryWide" type="submit">Загрузить в комнату</button></form><div className="installBar"><button onClick={()=>void playAll()} disabled={!state.videoId}>▶ Play для всех</button><button onClick={()=>void pauseAll()} disabled={!state.videoId}>Ⅱ Pause для всех</button><button onClick={()=>void seek()} disabled={!state.videoId}>↺ В начало</button></div></>}
 <form className="youtubeForm" onSubmit={suggest}><label htmlFor="suggest-url">Предложить следующее видео</label><input id="suggest-url" type="url" value={suggestion} onChange={e=>setSuggestion(e.target.value)} placeholder="Ссылка на YouTube" required/><button className="primaryWide" type="submit">＋ Добавить в очередь</button></form>
 <h3>Очередь предложений ({queue.length})</h3>{queue.length===0?<p className="hint">Пока предложений нет.</p>:<div className="queue">{queue.map((item,i)=><div className="queueItem" key={item.id}><span className="queueNum">{i+1}</span><div><b>{item.title}</b><small>{item.videoId}</small></div>{isHost&&<button type="button" onClick={()=>{setUrl("https://www.youtube.com/watch?v="+item.videoId);setTitle(item.title);setNotice("Ссылка перенесена в форму ведущего. Нажмите «Загрузить в комнату», когда будете готовы.")}}>Выбрать</button>}</div>)}</div>}
 {notice&&<p className="hint" role="status">{notice}</p>}{error&&<p className="error" role="alert">{error}</p>}<p className="hint">Встраивание зависит от настроек владельца ролика и ограничений YouTube. На телефоне может потребоваться ручное нажатие ▶ для старта со звуком.</p></section></main>
}
