"use client";

import { useEffect, useRef, useState } from "react";
import Hls from "hls.js";

type State={url:string;playing:boolean;position:number;updatedAt:number;title:string};
type Anime=Record<string,any>;
const initial:State={url:"",playing:false,position:0,updatedAt:Date.now(),title:"Пока ничего не включено"};
function pick<T=any>(obj:any,keys:string[],fallback?:T):T{for(const key of keys)if(obj?.[key]!==undefined&&obj?.[key]!==null)return obj[key] as T;return fallback as T}
function unwrap(data:any):any{let value=data;for(let i=0;i<6;i++){const next=value?.response??value?.data;if(!next||next===value)break;value=next}return value}
function findVideos(value:any,depth=0):any[]{if(!value||depth>6)return [];if(Array.isArray(value.videos))return value.videos;for(const key of ["response","data","anime","result","item"]){const found=findVideos(value[key],depth+1);if(found.length)return found}return []}
function animeName(a:any){const n=pick(a,["title","name","title_ru","russian"],"Без названия");return typeof n==="object"?pick(n,["ru","russian","english","original"],"Без названия"):n}

export default function Home(){
 const[state,setState]=useState<State>(initial),[admin,setAdmin]=useState(false),[url,setUrl]=useState(""),[title,setTitle]=useState(""),[publicKey,setPublicKey]=useState(""),[privateKey,setPrivateKey]=useState(""),[keysAdded,setKeysAdded]=useState(false),[serverKeysConfigured,setServerKeysConfigured]=useState(false),[room,setRoom]=useState("main"),[query,setQuery]=useState(""),[results,setResults]=useState<Anime[]>([]),[selected,setSelected]=useState<Anime|null>(null),[apiBusy,setApiBusy]=useState(false),[apiError,setApiError]=useState(""),[notice,setNotice]=useState(""),[playerStatus,setPlayerStatus]=useState("Нет серии"),[playerError,setPlayerError]=useState("");
 const video=useRef<HTMLVideoElement>(null);
 const [selectedEpisode,setSelectedEpisode]=useState<any|null>(null);
 useEffect(()=>{setRoom(location.hash.slice(1)||"main")},[]);
 useEffect(()=>{try{setPublicKey(sessionStorage.getItem("yummy_public")||"");setPrivateKey(sessionStorage.getItem("yummy_private")||"");setKeysAdded(sessionStorage.getItem("yummy_keys_ok")==="1")}catch{}},[]);
 useEffect(()=>{fetch("/api/yummy",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"config"}),cache:"no-store"}).then(r=>r.ok?r.json():null).then(x=>setServerKeysConfigured(Boolean(x?.configured))).catch(()=>setServerKeysConfigured(false))},[]);
 useEffect(()=>{const load=async()=>{try{const r=await fetch("/api/state?room="+encodeURIComponent(room),{cache:"no-store"});if(r.ok){const x=await r.json();if(x.state)setState(x.state)}}catch{}};load();const id=setInterval(load,700);return()=>clearInterval(id)},[room]);
 useEffect(()=>{const v=video.current;if(!v||!state.url)return;const p=state.playing?state.position+(Date.now()-state.updatedAt)/1000:state.position;if(Math.abs(v.currentTime-p)>0.8)v.currentTime=Math.max(0,p);if(state.playing)v.play().catch(()=>{}) ;else v.pause()},[state]);
 useEffect(()=>{const v=video.current;if(!v||!state.url)return;let cancelled=false;let hls:Hls|null=null;let dash:any=null;setPlayerError("");setPlayerStatus("Загружаю серию…");const onLoaded=()=>setPlayerStatus("Серия загружена ✓");const onWaiting=()=>setPlayerStatus("Буферизация…");const onPlaying=()=>setPlayerStatus("▶ Воспроизводится");const onError=()=>{const e=v.error;setPlayerError(e?.message?`Плеер: ${e.message}`:"Плеер не смог загрузить поток")};v.addEventListener("loadeddata",onLoaded);v.addEventListener("waiting",onWaiting);v.addEventListener("playing",onPlaying);v.addEventListener("error",onError);if(/\.mpd(?:$|[?#])/i.test(state.url)||/[?&]type=mpd(?:&|$)/i.test(state.url)){
  import("dashjs").then((dashjs:any)=>{if(cancelled)return;dash=dashjs.MediaPlayer().create();dash.initialize(v,state.url,false);dash.on(dashjs.MediaPlayer.events.ERROR,(e:any)=>setPlayerError("DASH: "+(e?.error?.message||e?.event?.message||"ошибка загрузки манифеста/сегментов")))}).catch(()=>setPlayerError("DASH: не удалось загрузить плеер"));
 }else if(/\.m3u8/i.test(state.url)||/[?&]type=m3u8(?:&|$)/i.test(state.url)){
  if(v.canPlayType("application/vnd.apple.mpegurl")){v.src=state.url;v.load()}
  else if(Hls.isSupported()){
   hls=new Hls({enableWorker:true,maxBufferLength:30,backBufferLength:30});
   hls.loadSource(state.url);hls.attachMedia(v);
   hls.on(Hls.Events.ERROR,(_,d)=>{
    if(!d.fatal)return;
    if(d.type===Hls.ErrorTypes.MEDIA_ERROR){setPlayerError("HLS: ошибка формата/кодека. Пробую восстановление…");try{hls?.recoverMediaError()}catch{}}
    else if(d.type===Hls.ErrorTypes.NETWORK_ERROR){setPlayerError("HLS: сеть/доступ к сегментам. Пробую переподключение…");try{hls?.startLoad()}catch{}}
    else setPlayerError("HLS: поток недоступен");
   })
  }else setPlayerError("Этот браузер не поддерживает HLS")
 }else{v.src=state.url;v.load()}return()=>{cancelled=true;v.removeEventListener("loadeddata",onLoaded);v.removeEventListener("waiting",onWaiting);v.removeEventListener("playing",onPlaying);v.removeEventListener("error",onError);hls?.destroy();dash?.reset();}},[state.url]);
 const publish=async(patch:Partial<State>)=>{const next={...state,...patch,updatedAt:Date.now()};setState(next);await fetch("/api/state?room="+encodeURIComponent(room),{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(next)}).catch(()=>{})};
 const pos=()=>video.current?.currentTime||state.position;
 const saveKeys=async()=>{setApiBusy(true);setApiError("");try{const r=await fetch("/api/yummy",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"search",query:"Киберпанк",token:publicKey,privateToken:privateKey})});const x=await r.json();if(!r.ok)throw new Error(x.error||"Ключи не прошли проверку");sessionStorage.setItem("yummy_public",publicKey);sessionStorage.setItem("yummy_private",privateKey);sessionStorage.setItem("yummy_keys_ok","1");setKeysAdded(true)}catch(e){setApiError(e instanceof Error?e.message:"Не удалось проверить ключ")}finally{setApiBusy(false)}};
 const clearKeys=()=>{setPublicKey("");setPrivateKey("");setKeysAdded(false);try{sessionStorage.clear()}catch{}};
 const searchAnime=async()=>{setApiBusy(true);setApiError("");setResults([]);setSelected(null);try{const r=await fetch("/api/yummy",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"search",query,token:publicKey,privateToken:privateKey})});const x=await r.json();if(!r.ok)throw new Error(x.error||"Ошибка API");const root=unwrap(x.data);const list=Array.isArray(root)?root:(Array.isArray(root?.items)?root.items:(Array.isArray(root?.results)?root.results:[]));setResults(list);if(!list.length)setApiError("Ничего не найдено")}catch(e){setApiError(e instanceof Error?e.message:"Ошибка поиска")}finally{setApiBusy(false)}};
 const loadAnime=async(anime:Anime)=>{setApiBusy(true);setApiError("");setSelected(anime);try{const id=pick(anime,["id","anime_id","animeId"]);const alias=pick(anime,["anime_url","url","alias","slug"]);const r=await fetch("/api/yummy",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"anime",id:id??alias,token:publicKey,privateToken:privateKey})});const x=await r.json();if(!r.ok)throw new Error(x.error||"Ошибка API");setSelected(unwrap(x.data))}catch(e){setApiError(e instanceof Error?e.message:"Ошибка загрузки тайтла")}finally{setApiBusy(false)}};
 const chooseVideo=async(source:Anime)=>{setApiBusy(true);setSelectedEpisode(source);setApiError("");try{const media=pick(source,["url","src","file","stream_url","video_url"]);if(typeof media==="string"&&/^https?:\/\/(.+\.(mp4|m3u8)(\?.*)?$)/i.test(media)){setUrl(media);setTitle(`${animeName(selected)} — серия ${pick(source,["number","episode"],"")}`.trim());setNotice("Серия добавлена. Теперь нажми «Установить».");return}const iframe=pick(source,["iframe_url","iframeUrl"]);if(typeof iframe!=="string")throw new Error("Источник не содержит видео");const r=await fetch("/api/yummy",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"resolve",iframe,token:publicKey,privateToken:privateKey})});const x=await r.json();if(!r.ok)throw new Error(x.error||"Не удалось получить поток");const first=x.sources?.find((s:any)=>s.quality==="720p")||x.sources?.find((s:any)=>/m3u8|mp4/i.test(s.url))||x.sources?.[0];if(!first?.url)throw new Error("Прямой поток не найден");setUrl(first.url);setTitle(`${animeName(selected)} — серия ${pick(source,["number","episode"],"")}`.trim());setNotice(`Найден поток ${first.quality||""}. Теперь нажми «Установить».`)}catch(e){setApiError(e instanceof Error?e.message:"Не удалось получить видео")}finally{setApiBusy(false)}};
 const install=async()=>{if(!url)return;setPlayerError("");setPlayerStatus("Готовлю серию…");await publish({url,title:title||"TogetherTV",playing:false,position:0});setNotice("Серия установлена. Плеер должен показать «Загружаю серию…». Дождись «Серия загружена ✓», затем запускай.");};
 const playAll=async()=>{const p=pos();await publish({playing:true,position:p});const v=video.current;if(v){v.currentTime=p;try{await v.play()}catch{setNotice("На этом телефоне браузер заблокировал автозапуск. Нажми ▶ на самом плеере один раз.")}}};
 const pauseAll=async()=>{await publish({playing:false,position:pos()});video.current?.pause()};
 const videos=findVideos(selected);

 return <main><header><div><b className="logo">TogetherTV</b><span className="muted"> watch party</span></div><button className="ghost" onClick={()=>setAdmin(!admin)}>{admin?"Закрыть админку":"Админ"}</button></header><div className="room">Комната: <b>{room}</b></div>
 <section className="hero"><div className="player"><video ref={video} controls playsInline/>{!state.url&&<div className="empty"><div className="play">▶</div><h1>Готовы смотреть вместе</h1><p>Сначала выбери серию в админке.</p></div>}</div><div className="playerStatus"><b>{playerStatus}</b>{playerError&&<span className="error">{playerError}</span>}</div><div className="now"><span>Сейчас смотрим</span><strong>{state.title}</strong><i className={state.playing?"live":""}>{state.playing?"● PLAY":"Ⅱ PAUSE"}</i></div></section>
 {admin&&<aside className="admin"><h2>Панель администратора</h2>
 {!(serverKeysConfigured||keysAdded)?<div className="keysBox"><h3>🔐 Ключи YummyAnime</h3><p className="hint">Public и Private ключи используются только в этом браузере.</p><label>Public key <small>X-Application</small><input type="password" value={publicKey} onChange={e=>setPublicKey(e.target.value)} placeholder="Public key"/></label><label>Private key<input type="password" value={privateKey} onChange={e=>setPrivateKey(e.target.value)} placeholder="Private key"/></label><button className="primaryWide" onClick={saveKeys} disabled={apiBusy||!publicKey.trim()}>{apiBusy?"Проверяю...":"Добавить ключи"}</button>{apiError&&<p className="error">{apiError}</p>}</div>:<div className="keysAdded"><span>✓ {serverKeysConfigured?"YummyAnime настроен на сервере":"Ключи YummyAnime добавлены"}</span>{!serverKeysConfigured&&<button className="mini" onClick={clearKeys}>Изменить</button>}</div>}
 <div className="yummy"><h3>🔎 Поиск аниме</h3><div className="searchRow"><input value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>e.key==="Enter"&&searchAnime()} placeholder="Например: Киберпанк"/><button onClick={searchAnime} disabled={apiBusy||!(serverKeysConfigured||keysAdded)||!query.trim()}>{apiBusy?"...":"Найти"}</button></div>{apiError&&(serverKeysConfigured||keysAdded)&&<p className="error">{apiError}</p>}{notice&&<p className="hint">{notice}</p>}
 {!!results.length&&<div className="results"><div className="muted resultCount">Найдено: {results.length}</div>{results.map((a,i)=>{const id=pick(a,["id","anime_id","animeId"],i);return <button className="result" key={String(id)+i} onClick={()=>loadAnime(a)}><b>{animeName(a)}</b><small>{pick(a,["year","type","anime_url","url"],"Нажми, чтобы открыть")}</small></button>})}</div>}
 {selected&&<div className="animeCard"><h3>{animeName(selected)}</h3><p className="muted">Выбери серию</p>{videos.length?<div className="sources">{videos.map((v:any,i:number)=><button className={"source"+(selectedEpisode===v?" selected":"")} key={i} onClick={()=>chooseVideo(v)} disabled={apiBusy}><b>{pick(v?.data||v,["player","name","dubbing"],"Источник")}</b><span>Серия {pick(v,["number","episode"],i+1)} · {selectedEpisode===v?"выбрана":"выбрать"}</span></button>)}</div>:<p className="hint">Серии не вернулись из API для этого тайтла.</p>}</div>}</div>
 <label>Ссылка на видео <small>MP4 / M3U8 / разрешённый источник</small><input value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://..."/></label><label>Название<input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Название серии"/></label>
 <div className="installBar"><div className="selection"><b>{title||"Серия не выбрана"}</b><span>{selectedEpisode?"Готово к установке":"Выбери серию выше"}</span></div><button className="installMain" onClick={install} disabled={!url}>Установить</button><button onClick={playAll} disabled={!state.url}>▶ Play для всех</button><button onClick={pauseAll} disabled={!state.url}>Ⅱ Pause для всех</button><button onClick={()=>publish({playing:false,position:0})} disabled={!state.url}>↺ В начало</button></div>
 <p className="hint">Если телефон впервые запускает звук, нажми ▶ на самом плеере один раз. После этого синхронизация Play/Pause работает через состояние комнаты.</p></aside>}</main>
}
